name: CI
on:
  push:
    branches:
      # Change this if your primary branch is not main
      - main
    pull_request:

  # Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Test
        run: yarn affected:test --parallel=5

      - name: Build
        run: yarn affected:build --parallel=5
